Repository damian19dk/Project-PixBlocks-Addition, pull requests merged in 2019-06, with the labels that each got.

#50 Fe test jwt
  doc/postman.json
  web/src/app/app.module.ts
  web/src/app/courses/course-manager/course-manager.component.html
  web/src/app/courses/edit-course/edit-course.component.html
  web/src/app/courses/new-course/new-course.component.ts
  web/src/app/header/header.component.html
  web/src/app/interceptors/jwt-interceptor.ts
  web/src/app/lessons/new-lesson/new-lesson.component.html
  web/src/app/lessons/new-lesson/new-lesson.component.ts
  web/src/app/page-not-found/page-not-found.component.html
  web/src/app/services/authentication.service.ts
  web/src/app/show-video/show-video.component.ts
  web/src/app/unauthorized/unauthorized.component.html
  web/src/app/user/login/login.component.ts
  web/src/app/user/registration/registration.component.ts
Labels: bug, frontend

#51 fix
  api/PixBlocks_Addition.Domain/Repositories/MediaRepo/CourseRepository.cs
  api/PixBlocks_Addition.Domain/Repositories/MediaRepo/ExercisieRepository.cs
  api/PixBlocks_Addition.Domain/Repositories/MediaRepo/LessonRepository.cs
  api/PixBlocks_Addition.Domain/Repositories/MediaRepo/VideoRepository.cs
Labels: backend, bug

#56 Be task 86
  api/PixBlocks_Addition.Api/Controllers/IdentityController.cs
  api/PixBlocks_Addition.Api/Controllers/UserController.cs
  api/PixBlocks_Addition.Infrastructure/Services/IIdentityService.cs
  api/PixBlocks_Addition.Infrastructure/Services/IUserService.cs
  api/PixBlocks_Addition.Infrastructure/Services/IdentityService.cs
  api/PixBlocks_Addition.Infrastructure/Services/UserService.cs
Labels: backend

#62 fixed some exceptions
  api/PixBlocks_Addition.Domain/Exceptions/MyCodesNumbers.cs
  api/PixBlocks_Addition.Infrastructure/Services/MediaServices/ChangeMediaHandler.cs
  api/PixBlocks_Addition.Infrastructure/Services/MediaServices/CourseService.cs
Labels: backend

#63 Fe task 75
  web/src/app/app.module.ts
  web/src/app/courses/edit-course/edit-course.component.html
  web/src/app/courses/new-course/new-course.component.html
  web/src/app/courses/new-course/new-course.component.ts
  web/src/app/footer/footer.component.html
  web/src/app/home/home.component.html
  web/src/app/interceptors/unauthorized-interceptor.ts
  web/src/app/services/authentication.service.ts
  web/src/app/video/show-video/overview/overview.component.html
  web/src/app/video/show-video/questions/questions.component.css
  web/src/app/video/show-video/show-video.component.css
  web/src/app/video/show-video/show-video.component.html
Labels: frontend

#64 New Homepage
  web/src/app/home/home.component.css
  web/src/app/home/home.component.html
  web/src/assets/svg/undraw_click_here_2li1.svg
  web/src/assets/svg/undraw_code_review_l1q9.svg
  web/src/assets/svg/undraw_connected_world_wuay.svg
  web/src/assets/svg/undraw_hacker_mind_6y85.svg
  web/src/assets/svg/undraw_knowledge_g5gf.svg
  web/src/assets/svg/undraw_noted_pc9f.svg
  web/src/assets/svg/undraw_solution_mindset_34bi.svg
  web/src/assets/svg/undraw_voice_interface_eckp.svg
  web/src/assets/svg/undraw_web_developer_p3e5.svg
Labels: frontend

#65 Fe task 91
  web/src/app/footer/footer.component.css
  web/src/app/footer/footer.component.html
  web/src/assets/img/sygnet-1.png
  web/src/assets/img/unia0.png
  web/src/assets/img/unia06.png
  web/src/assets/img/unia07.png
  web/src/assets/img/unia08.png
  web/src/assets/svg/undraw_contact_us_15o2(1).svg
  web/src/assets/svg/undraw_programming_2svr(1).svg
Labels: frontend

#66 Fe task 92
  web/src/app/video/add-video/add-video.component.css
  web/src/app/video/add-video/add-video.component.html
  web/src/assets/svg/undraw_media_player_ylg8(1).svg
Labels: frontend

#67 Fe task 75
  api/PixBlocks_Addition.Api/appsettings.json
  web/src/app/courses/course-thumbnail/course-thumbnail.component.html
  web/src/app/courses/course-thumbnail/course-thumbnail.component.ts
  web/src/app/courses/new-course/new-course.component.html
  web/src/app/error-pages/functionality-not-prepared/functionality-not-prepared.component.html
  web/src/app/error-pages/page-not-found/page-not-found.component.html
  web/src/app/error-pages/unauthorized/unauthorized.component.html
  web/src/app/home/home.component.css
  web/src/app/models/courseDto.model.ts
  web/src/app/services/course.service.ts
  web/src/app/services/tag.service.ts
  web/src/app/user/login/login.component.html
  web/src/app/user/login/login.component.ts
  web/src/app/user/registration/registration.component.html
  web/src/app/video/show-video/show-video.component.css
  web/src/app/video/show-video/show-video.component.html
  web/src/app/video/show-video/show-video.component.ts
  web/src/app/video/video-thumbnail/video-thumbnail.component.css
  web/src/app/video/video-thumbnail/video-thumbnail.component.html
  web/src/assets/svg/undraw_Outer_space_drqu.svg
  web/src/assets/svg/undraw_authentication_fsn5.svg
  web/src/assets/svg/undraw_bug_fixing_oc7a.svg
  web/src/assets/svg/undraw_chat_1wo5.svg
  web/src/assets/svg/undraw_development_ouy3.svg
  web/src/assets/svg/undraw_forgot_password_gi2d.svg
  web/src/assets/svg/undraw_lost_bqr2.svg
  web/src/assets/svg/undraw_media_player_ylg8.svg
  web/src/assets/svg/undraw_notify_88a4.svg
  web/src/assets/svg/undraw_page_not_found_su7k.svg
  web/src/assets/svg/undraw_personal_data_29co.svg
  web/src/assets/svg/undraw_personal_site_xyd1.svg
  web/src/assets/svg/undraw_photo_4yb9.svg
  web/src/assets/svg/undraw_profile_pic_ic5t.svg
  web/src/assets/svg/undraw_programmer_imem.svg
  web/src/assets/svg/undraw_programming_2svr.svg
  web/src/assets/svg/undraw_questions_75e0.svg
  web/src/assets/svg/undraw_security_o890.svg
  web/src/assets/svg/undraw_setup_wizard_r6mr.svg
  web/src/assets/svg/undraw_static_assets_rpm6.svg
  web/src/assets/svg/undraw_superhero_kguv.svg
  web/src/assets/svg/undraw_warning_cyit.svg
  web/src/assets/svg/undraw_winners_ao2o.svg
Labels: frontend

#69 Fe task 93
  web/src/app/home/home.component.css
  web/src/app/home/home.component.html
Labels: frontend

#75 Fe task 75
  web/src/app/app.component.ts
  web/src/app/app.module.ts
  web/src/app/common/search-bar/search-bar.component.html
  web/src/app/common/search-bar/search-bar.component.ts
  web/src/app/courses/course-thumbnail/course-thumbnail.component.css
  web/src/app/courses/course-thumbnail/course-thumbnail.component.html
  web/src/app/courses/course-thumbnail/course-thumbnail.component.ts
  web/src/app/courses/edit-course/edit-course.component.html
  web/src/app/courses/edit-course/edit-course.component.ts
  web/src/app/courses/new-course/new-course.component.html
  web/src/app/courses/new-course/new-course.component.ts
  web/src/app/home/home.component.html
  web/src/app/home/home.component.ts
  web/src/app/lessons/new-lesson/new-lesson.component.html
  web/src/app/lessons/new-lesson/new-lesson.component.ts
  web/src/app/models/hostedVideoDocument.model.ts
  web/src/app/models/videoDto.model.ts
  web/src/app/services/data.service.ts
  web/src/app/services/tag.service.ts
  web/src/app/services/video.service.ts
  web/src/app/user/profile/profile.component.css
  web/src/app/user/profile/profile.component.html
  web/src/app/user/profile/profile.component.spec.ts
  web/src/app/user/profile/profile.component.ts
  web/src/app/video/add-video/add-video.component.html
  web/src/app/video/add-video/add-video.component.ts
  web/src/app/video/show-video/overview/overview.component.ts
  web/src/app/video/show-video/show-video.component.css
  web/src/app/video/show-video/show-video.component.html
  web/src/app/video/show-video/show-video.component.ts
  web/src/app/video/video-thumbnail/video-thumbnail.component.html
  web/src/app/video/video-thumbnail/video-thumbnail.component.ts
  web/src/environments/environment.ts
Labels: frontend

#77 Fe task 97
  web/package.json
  web/src/app/common/search-bar/search-bar.component.html
  web/src/app/courses/course-manager/course-manager.component.html
  web/src/app/courses/course-thumbnail/course-thumbnail.component.html
  web/src/app/courses/new-course/new-course.component.html
  web/src/app/error-pages/functionality-not-prepared/functionality-not-prepared.component.html
  web/src/app/error-pages/page-not-found/page-not-found.component.html
  web/src/app/error-pages/unauthorized/unauthorized.component.html
  web/src/app/footer/footer.component.html
  web/src/app/header/header.component.html
  web/src/app/home/home.component.html
  web/src/app/lessons/lesson-manager/lesson-manager.component.html
  web/src/app/lessons/new-lesson/new-lesson.component.html
  web/src/app/user/login/login.component.html
  web/src/app/user/registration/registration.component.html
  web/src/app/video/add-video/add-video.component.html
  web/src/app/video/show-video/overview/overview.component.html
  web/src/app/video/show-video/questions/questions.component.html
  web/src/translate/messages.en.xlf
  web/src/translate/messages.pl.xlf
  web/src/translate/messages.xlf
Labels: enhancement, frontend

#78 Fe task 75
  web/src/app/app.component.ts
  web/src/app/app.module.ts
  web/src/app/common/search-bar/search-bar.component.css
  web/src/app/common/search-bar/search-bar.component.html
  web/src/app/common/search-bar/search-bar.component.ts
  web/src/app/courses/course-thumbnail/course-thumbnail.component.ts
  web/src/app/courses/new-course/new-course.component.ts
  web/src/app/header/header.component.css
  web/src/app/header/header.component.html
  web/src/app/header/header.component.ts
  web/src/app/home/home.component.html
  web/src/app/home/home.component.ts
  web/src/app/lessons/edit-lesson/edit-lesson.component.html
  web/src/app/lessons/edit-lesson/edit-lesson.component.ts
  web/src/app/lessons/lesson-manager/lesson-manager.component.html
  web/src/app/lessons/lesson-thumbnail/lesson-thumbnail.component.css
  web/src/app/lessons/lesson-thumbnail/lesson-thumbnail.component.html
  web/src/app/lessons/lesson-thumbnail/lesson-thumbnail.component.spec.ts
  web/src/app/lessons/lesson-thumbnail/lesson-thumbnail.component.ts
  web/src/app/lessons/new-lesson/new-lesson.component.ts
  web/src/app/models/userDocument.model.ts
  web/src/app/services/auth.service.ts
  web/src/app/services/user.service.spec.ts
  web/src/app/services/user.service.ts
  web/src/app/user/login/login.component.ts
  web/src/app/user/profile/change-email/change-email.component.css
  web/src/app/user/profile/change-email/change-email.component.html
  web/src/app/user/profile/change-email/change-email.component.spec.ts
  web/src/app/user/profile/change-email/change-email.component.ts
  web/src/app/user/profile/change-password/change-password.component.css
  web/src/app/user/profile/change-password/change-password.component.html
  web/src/app/user/profile/change-password/change-password.component.spec.ts
  web/src/app/user/profile/change-password/change-password.component.ts
  web/src/app/user/profile/profile.component.html
  web/src/app/user/profile/profile.component.ts
  web/src/app/user/registration/registration.component.ts
  web/src/app/video/add-video/add-video.component.ts
  web/src/environments/environment.ts
  web/src/translate/messages.en.xlf
  web/src/translate/messages.xlf
Labels: frontend
