Repository damian19dk/Project-PixBlocks-Addition, pull requests merged in 2019-05, with the labels that each got.

#12 Fe task2 21
  web/angular.json
  web/package.json
  web/src/app/add-video/add-video.component.css
  web/src/app/add-video/add-video.component.html
  web/src/app/add-video/add-video.component.spec.ts
  web/src/app/add-video/add-video.component.ts
  web/src/app/adresses.json
  web/src/app/app.component.css
  web/src/app/app.component.html
  web/src/app/app.component.ts
  web/src/app/app.module.ts
  web/src/app/footer/footer.component.css
  web/src/app/footer/footer.component.html
  web/src/app/header/header.component.css
  web/src/app/header/header.component.html
  web/src/app/header/header.component.ts
  web/src/app/home/home.component.css
  web/src/app/home/home.component.html
  web/src/app/labels.json
  web/src/app/models/user.model.ts
  web/src/app/page-not-found/page-not-found.component.html
  web/src/app/services/authentication.service.ts
  web/src/app/unauthorized/unauthorized.component.html
  web/src/app/upload-video/upload-video.component.css
  web/src/app/upload-video/upload-video.component.html
  web/src/app/upload-video/upload-video.component.spec.ts
  web/src/app/upload-video/upload-video.component.ts
  web/src/app/user/login/login.component.html
  web/src/app/user/login/login.component.ts
  web/src/app/user/registration/registration.component.html
  web/src/app/user/registration/registration.component.ts
  web/src/styles.css
  web/src/translate/messages.en.xlf
  web/src/translate/messages.pl.xlf
  web/src/translate/messages.xlf
  web/tsconfig.json
Labels: enhancement

#39 Fe task 80
  web/src/app/courses/new-course/new-course.component.html
  web/src/app/courses/new-course/new-course.component.ts
  web/src/app/lessons/new-lesson/new-lesson.component.html
  web/src/app/lessons/new-lesson/new-lesson.component.ts
  web/src/app/services/authentication.service.ts
  web/src/app/user/login/login.component.html
  web/src/app/user/login/login.component.ts
  web/src/app/user/registration/registration.component.html
  web/src/app/user/registration/registration.component.ts
Labels: frontend

#40 BIG FIX
  web/src/app/lessons/new-lesson/new-lesson.component.html
  web/src/app/show-video/overview/overview.component.html
  web/src/app/show-video/overview/overview.component.ts
  web/src/app/show-video/show-video.component.html
  web/src/app/show-video/show-video.component.ts
  web/src/index.html
Labels: frontend

#44 added more exceptions
  api/PixBlocks_Addition.Api/Controllers/ImageController.cs
  api/PixBlocks_Addition.Domain/Entities/CustomImage.cs
  api/PixBlocks_Addition.Domain/Exceptions/MyCodes.cs
  api/PixBlocks_Addition.Domain/Exceptions/MyCodesNumbers.cs
  api/PixBlocks_Addition.Infrastructure/Services/ImageService.cs
  api/PixBlocks_Addition.Infrastructure/Services/MediaServices/CourseService.cs
  api/PixBlocks_Addition.Infrastructure/Services/MediaServices/ExerciseService.cs
  api/PixBlocks_Addition.Infrastructure/Services/MediaServices/LessonService.cs
  api/PixBlocks_Addition.Infrastructure/Services/MediaServices/VideoService.cs
Labels: backend

#46 Fe test jwt
  doc/postman.json
  web/src/app/courses/course-manager/course-manager.component.html
  web/src/app/courses/edit-course/edit-course.component.html
  web/src/app/courses/new-course/new-course.component.html
  web/src/app/courses/new-course/new-course.component.ts
  web/src/app/header/header.component.html
  web/src/app/models/courseDto.model.ts
  web/src/app/services/authentication.service.ts
  web/src/app/services/course.service.ts
  web/src/app/services/lesson.service.ts
  web/src/app/services/video.service.ts
  web/src/app/user/login/login.component.ts
  web/src/app/user/registration/registration.component.ts
  web/src/app/video-thumbnail/video-thumbnail.component.css
  web/src/environments/environment.prod.ts
  web/src/environments/environment.ts
Labels: frontend

#47 Fe task 71
  node_modules/ng-multiselect-dropdown/README.md
  node_modules/ng-multiselect-dropdown/bundles/ng-multiselect-dropdown.umd.js
  node_modules/ng-multiselect-dropdown/bundles/ng-multiselect-dropdown.umd.js.map
  node_modules/ng-multiselect-dropdown/bundles/ng-multiselect-dropdown.umd.min.js
  node_modules/ng-multiselect-dropdown/bundles/ng-multiselect-dropdown.umd.min.js.map
  node_modules/ng-multiselect-dropdown/click-outside.directive.d.ts
  node_modules/ng-multiselect-dropdown/esm2015/click-outside.directive.js
  node_modules/ng-multiselect-dropdown/esm2015/list-filter.pipe.js
  node_modules/ng-multiselect-dropdown/esm2015/multiselect.component.js
  node_modules/ng-multiselect-dropdown/esm2015/multiselect.model.js
  node_modules/ng-multiselect-dropdown/esm2015/ng-multiselect-dropdown.js
  node_modules/ng-multiselect-dropdown/esm2015/ng-multiselect-dropdown.module.js
  node_modules/ng-multiselect-dropdown/esm2015/public_api.js
  node_modules/ng-multiselect-dropdown/esm5/click-outside.directive.js
  node_modules/ng-multiselect-dropdown/esm5/list-filter.pipe.js
  node_modules/ng-multiselect-dropdown/esm5/multiselect.component.js
  node_modules/ng-multiselect-dropdown/esm5/multiselect.model.js
  node_modules/ng-multiselect-dropdown/esm5/ng-multiselect-dropdown.js
  node_modules/ng-multiselect-dropdown/esm5/ng-multiselect-dropdown.module.js
  node_modules/ng-multiselect-dropdown/esm5/public_api.js
  node_modules/ng-multiselect-dropdown/fesm2015/ng-multiselect-dropdown.js
  node_modules/ng-multiselect-dropdown/fesm2015/ng-multiselect-dropdown.js.map
  node_modules/ng-multiselect-dropdown/fesm5/ng-multiselect-dropdown.js
  node_modules/ng-multiselect-dropdown/fesm5/ng-multiselect-dropdown.js.map
  node_modules/ng-multiselect-dropdown/list-filter.pipe.d.ts
  node_modules/ng-multiselect-dropdown/multiselect.component.d.ts
  node_modules/ng-multiselect-dropdown/multiselect.model.d.ts
  node_modules/ng-multiselect-dropdown/ng-multiselect-dropdown.d.ts
  node_modules/ng-multiselect-dropdown/ng-multiselect-dropdown.metadata.json
  node_modules/ng-multiselect-dropdown/ng-multiselect-dropdown.module.d.ts
  node_modules/ng-multiselect-dropdown/package.json
  node_modules/ng-multiselect-dropdown/public_api.d.ts
  node_modules/tslib/.gitattributes
  node_modules/tslib/CopyrightNotice.txt
  node_modules/tslib/LICENSE.txt
  node_modules/tslib/README.md
  node_modules/tslib/bower.json
  node_modules/tslib/docs/generator.md
  node_modules/tslib/package.json
  node_modules/tslib/tslib.d.ts
  node_modules/tslib/tslib.es6.html
  node_modules/tslib/tslib.es6.js
  node_modules/tslib/tslib.html
  node_modules/tslib/tslib.js
  package-lock.json
  web/package-lock.json
  web/package.json
  web/src/app/header/header.component.css
  web/src/app/header/header.component.html
  web/src/app/header/header.component.ts
  web/src/app/home/home.component.html
  web/src/app/show-video/show-video.component.css
Labels: frontend

#48 Fix them all
  node_modules/ng-multiselect-dropdown/README.md
  node_modules/ng-multiselect-dropdown/bundles/ng-multiselect-dropdown.umd.js
  node_modules/ng-multiselect-dropdown/bundles/ng-multiselect-dropdown.umd.js.map
  node_modules/ng-multiselect-dropdown/bundles/ng-multiselect-dropdown.umd.min.js
  node_modules/ng-multiselect-dropdown/bundles/ng-multiselect-dropdown.umd.min.js.map
  node_modules/ng-multiselect-dropdown/click-outside.directive.d.ts
  node_modules/ng-multiselect-dropdown/esm2015/click-outside.directive.js
  node_modules/ng-multiselect-dropdown/esm2015/list-filter.pipe.js
  node_modules/ng-multiselect-dropdown/esm2015/multiselect.component.js
  node_modules/ng-multiselect-dropdown/esm2015/multiselect.model.js
  node_modules/ng-multiselect-dropdown/esm2015/ng-multiselect-dropdown.js
  node_modules/ng-multiselect-dropdown/esm2015/ng-multiselect-dropdown.module.js
  node_modules/ng-multiselect-dropdown/esm2015/public_api.js
  node_modules/ng-multiselect-dropdown/esm5/click-outside.directive.js
  node_modules/ng-multiselect-dropdown/esm5/list-filter.pipe.js
  node_modules/ng-multiselect-dropdown/esm5/multiselect.component.js
  node_modules/ng-multiselect-dropdown/esm5/multiselect.model.js
  node_modules/ng-multiselect-dropdown/esm5/ng-multiselect-dropdown.js
  node_modules/ng-multiselect-dropdown/esm5/ng-multiselect-dropdown.module.js
  node_modules/ng-multiselect-dropdown/esm5/public_api.js
  node_modules/ng-multiselect-dropdown/fesm2015/ng-multiselect-dropdown.js
  node_modules/ng-multiselect-dropdown/fesm2015/ng-multiselect-dropdown.js.map
  node_modules/ng-multiselect-dropdown/fesm5/ng-multiselect-dropdown.js
  node_modules/ng-multiselect-dropdown/fesm5/ng-multiselect-dropdown.js.map
  node_modules/ng-multiselect-dropdown/list-filter.pipe.d.ts
  node_modules/ng-multiselect-dropdown/multiselect.component.d.ts
  node_modules/ng-multiselect-dropdown/multiselect.model.d.ts
  node_modules/ng-multiselect-dropdown/ng-multiselect-dropdown.d.ts
  node_modules/ng-multiselect-dropdown/ng-multiselect-dropdown.metadata.json
  node_modules/ng-multiselect-dropdown/ng-multiselect-dropdown.module.d.ts
  node_modules/ng-multiselect-dropdown/package.json
  node_modules/ng-multiselect-dropdown/public_api.d.ts
  node_modules/tslib/.gitattributes
  node_modules/tslib/CopyrightNotice.txt
  node_modules/tslib/LICENSE.txt
  node_modules/tslib/README.md
  node_modules/tslib/bower.json
  node_modules/tslib/docs/generator.md
  node_modules/tslib/package.json
  node_modules/tslib/tslib.d.ts
  node_modules/tslib/tslib.es6.html
  node_modules/tslib/tslib.es6.js
  node_modules/tslib/tslib.html
  node_modules/tslib/tslib.js
  npm-debug.log
  package-lock.json
Labels: bug
